### ISSUE TITLE
Empty board

### ISSUE THREAD

**Issue by Heideachim** [AuthenticEshkinKot/Taskodrome#10]
Upon opening the 'Taskodrom' menu entry, nothing happens. There is only a huge, gray area with nothing in it.
We are using MantisBT since several years and have 2000+ entries, so there definitely should be something.
MantisBT is 2.9.0, PHP is 7.1.12, Taskodrom is 1.2.1
There are no error messages in the console window (neither Firefox nor Chrome).
So what do I need to do to use it?

**Comment by AuthenticEshkinKot** [comment]
@Heideachim 
Could you post full log? On https://pastebin.com/, for example.

**Comment by Heideachim** [comment]
@AuthenticEshkinKot 
pastbin.com is blocked in our company... Log is here:

getIssuesRaw: exists - true    
getIssuesRaw: length - 569
getCooldownPeriod: cooldownPeriodDays - 14 cooldownPeriodHours - 0
getStatusesAllowanceMap: exists - true
getStatusesAllowanceMap: length - 569
getStatusColors: exists - true
getStatusColors: length - 44
getUsersRaw: exists - true
getUsersRaw: length - 18
NS_ERROR_FAILURE:     plugin_file.php:13
b.clear                   http://localhost/mantisbt/plugin_file.php:13:13943
draw                     http://localhost/mantisbt/plugin_file.php:43:3
draw                     http://localhost/mantisbt/plugin_file.php:64:5
init                        http://localhost/mantisbt/plugin_file.php:37:3
pageOnLoad         http://localhost/mantisbt/plugin_file.php:47:3

I am going to look into the NS_ERROR_FAILURE.

**Comment by Heideachim** [comment]
There is no error on Chrome, but exactly the same behaviour.
In Firefox, the NS_ERROR_FAILURE happens in easeljs-0.8.2-min.js. The first entries of the log appear instantly (the one from getIssuesRaw... to getUsersRaw...), thet it takes about 10 seconds for the NS_ERROR_FAILURE to show up. 
There is no entry in the apache log.
I have replaced all .htaccess with 'grant all'.
The whole thing runs in a VirtualBox, but there is internet access and all. 
MantisBT is accessed as 'localhost', might this be a problem?

**Comment by AuthenticEshkinKot** [comment]
@Heideachim 
In my case, MantisBT is hosted on 'localhost' and everything is OK.

**Comment by Heideachim** [comment]
I just un-installed all other plug-ins, downloaded Taskodrom again and installed ist again. Copy of mantisbt_2.0.0. Taskodrom reports its version as 1.3.0.
Behaviour is still the same: An immensly large, grey field without any entries. After some seconds, the console reports that NS_ERROR_FAILURE.

**Comment by Heideachim** [comment]
While Firefox and Chrome simply fail without saying much, IExplore reports the following: "Object does not support property or method". Highlighed in yellow is the following part of jquery-2.2.4.min.js: 
"return I||(I=n.Deferred(),"complete"===d.readyState||"loading"!==d.readyState&&!d.documentElement.doScroll?a.setTimeout(n.ready):(d.addEventListener("DOMContentLoaded",J),a.addEventListener("load",J))),I.promise(b)"

**Comment by Heideachim** [comment]
The problem must be inside the selected project. The project I normally work on is quite large. Seems that Taskodrom (or whoever) has problems with that.
If I select another project, it works as expected!
When I save the generated HTML code of the Taskodrom page, all the information of the project is there. It just cannot be displayed!
What can I do now?

**Comment by AuthenticEshkinKot** [comment]
Is there any NS_ERROR_FAILURE message in another project?

**Comment by Heideachim** [comment]
All projects that do not display have this NS_ERROR_FAILURE message. That are three projects. The other projects, about 5, which are smaller, do not have this message and they do display correctly.

**Comment by Heideachim** [comment]
If you want, I can send you a zip'ed version of a non-working page via PM.

**Comment by AuthenticEshkinKot** [comment]
Yes, it would be good.

**Comment by cedrickzepp** [comment]
![screenshot 2019-03-01 at 16 51 04](https://user-images.githubusercontent.com/47735589/53671076-7c27c500-3c42-11e9-946e-c75c01233955.png)
Same error for me:
