### ISSUE TITLE
Wrong color on assignment

### ISSUE THREAD

**Issue by meriadecgithub** [AuthenticEshkinKot/Taskodrome#12]
When I assign a Task to a user with taskodrome, the color of the status icon change.
But the status of the task don't change because I have set the parameter "$g_auto_set_status_to_assigned" to "OFF".
When I refresh the page, the color come back to the original color.

It's just a little display bug, but it disturb the users

**Comment by AuthenticEshkinKot** [comment]
Hi, @meriadecgithub !
I've fixed this bug in https://github.com/AuthenticEshkinKot/Taskodrome/commit/e35631827cdc04476462b5318b1f849febc674ce. Check it out, please.

**Comment by meriadecgithub** [comment]
I have checked, the bug is no more present, the color of the status doesn't change when I assign a task
Thanks !!
