### ISSUE TITLE
The PNG files cannot be loaded

### ISSUE THREAD

**Issue by Zipher04** [AuthenticEshkinKot/Taskodrome#15]
- The PNG files in {MantisBt}\plugins\Taskodrome\files\assets cannot be accessed. I thought the .htaccess file in folder {MantisBt}\plugins deny the privilege to access these files. 
- I copied the folder to {MantisBt}\images\Taskodrome and modified the path var in createPriorityMark() in grid_draw_utils.js to "images/Taskodrome/". The png files can be shown correctly.
- But this way broke the integration of the plugin. Is there a better way for this?
- My MantisBt version is 2.9.0.

**Comment by pluk77** [comment]
Don't think the issue here isthe permissions. From what I understand, plugins should actually load files differently.

line 615 in grid_draw_utils.js should read:

`var path = "plugin_file.php?file=Taskodrome/assets/";`

**Comment by AuthenticEshkinKot** [comment]
Recently, I've added .htaccess to assets directory, so it should work correclty.
