### ISSUE TITLE
Error in strings file?

### ISSUE THREAD

**Issue by Jay-Cee** [AuthenticEshkinKot/Taskodrome#19]
[strings_german.txt](https://github.com/AuthenticEshkinKot/Taskodrome/files/3941620/strings_german.txt)
Hello!

May it be there is an error in the "strings_english.txt" file.
After translation to german I stumbled over this line:
`$s_plugin_Taskodrome_no_status_transition = 'ERROR: Transition from "$1" to "$2" is forbidden';`
After "fiddling" a little (I'm not a programmer, sorry) I came over a solution which is similar to the last line where the parameters are not quoted, as well.
What works for me is:
`$s_plugin_Taskodrome_no_status_transition = 'FEHLER: Der Übergang von $1 zu $2 ist unzulässig';`
You may want to notice the missing quotation-marks just before and after the parameters.

For anyone who is interested the translation file is attached. Feel free to use or incorporate as you want ;-)
[strings_german.txt](https://github.com/AuthenticEshkinKot/Taskodrome/files/3941609/strings_german.txt)
<EDIT: now the correct german file. </EDIT>

**Comment by AuthenticEshkinKot** [comment]
Hello, @Jay-Cee !
Thanks for your help! These quotation marks are useless, so I removed them from strings_english.txt. Also, thanks for german translation!
