### ISSUE TITLE
Support for IE 11

### ISSUE THREAD

**Issue by johnzastrow** [AuthenticEshkinKot/Taskodrome#2]
In IE 11, nothing loads in the screen and the attached images are shown in the dev Window.
![ie11debugger](https://cloud.githubusercontent.com/assets/1213646/13572491/983a470e-e448-11e5-88f2-4f8ef93ebba2.png)
![ie11console](https://cloud.githubusercontent.com/assets/1213646/13572494/9d671b4e-e448-11e5-8830-e096b3a0f608.png)

**Comment by AuthenticEshkinKot** [comment]
Fixed

**Comment by asp272** [comment]
@AuthenticEshkinKot
![image](https://user-images.githubusercontent.com/7036724/36062255-e4ed2ac0-0e9a-11e8-8c33-ad9f452b83a9.png)
Аналогичные ошибки опять появились в IE11
